/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package di;


import di.container.DIContainer;
import di.container.DIContainerException;
import di.container.JsonDIContainer;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
        throws InterruptedException, ClassNotFoundException, DIContainerException, IOException {

    }
}
